# Step 1: Use the official Node.js image
FROM node:22

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Copy your application files into the container
COPY . /app

# Step 4: Install dependencies
RUN npm install

# Step 5: Start your scraper when the container is run
CMD ["npm", "run", "start"]

